"""One-time i18n translation generator.

Usage:
  cd /app/backend && python ../scripts/translate_ui.py

Reads the English string bundle from /app/frontend/src/i18n/strings.en.ts,
uses Claude Haiku via emergentintegrations to translate every value into
each target language, and writes /app/frontend/src/i18n/strings.<code>.ts.

Idempotent: running again overwrites the generated files.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path("/app/backend").resolve()))
from dotenv import load_dotenv  # noqa: E402
load_dotenv("/app/backend/.env")

from emergentintegrations.llm.chat import LlmChat, UserMessage  # noqa: E402

ROOT = Path("/app/frontend/src/i18n")
EN_FILE = ROOT / "strings.en.ts"

TARGETS = [
    ("hi", "Hindi (हिन्दी)"),
    ("mr", "Marathi (मराठी)"),
    ("gu", "Gujarati (ગુજરાતી)"),
    ("ta", "Tamil (தமிழ்)"),
    ("te", "Telugu (తెలుగు)"),
    ("kn", "Kannada (ಕನ್ನಡ)"),
    ("ml", "Malayalam (മലയാളം)"),
    ("bn", "Bengali (বাংলা)"),
    ("pa", "Punjabi (ਪੰਜਾਬੀ)"),
    ("or", "Odia (ଓଡ଼ିଆ)"),
]


def parse_en_object() -> dict[str, str]:
    """Very small parser for the `export const en = {...}` object literal."""
    src = EN_FILE.read_text(encoding="utf-8")
    start = src.index("export const en = {") + len("export const en = ")
    # Balanced-brace walk
    depth = 0
    end = start
    for i in range(start, len(src)):
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    obj_text = src[start:end]
    # Extract key: "value" pairs. Values are always double-quoted single-line strings in our bundle.
    pattern = re.compile(r"(\w+)\s*:\s*\"((?:[^\"\\]|\\.)*)\"", re.DOTALL)
    out = {}
    for m in pattern.finditer(obj_text):
        key = m.group(1)
        val = m.group(2).encode("utf-8").decode("unicode_escape") if "\\" in m.group(2) else m.group(2)
        out[key] = val
    return out


async def translate(lang_code: str, lang_name: str, en_map: dict[str, str]) -> dict[str, str]:
    api_key = os.environ["EMERGENT_LLM_KEY"]
    system_message = (
        "You are a professional software localization translator. You translate UI microcopy "
        "for a mobile business-card OCR + CRM app called CardVault. "
        "Keep the target language natural, concise, and idiomatic. "
        "Preserve every placeholder like {name}, punctuation, ellipses (…), and technical labels "
        "(SMTP, OCR, PIN, LinkedIn) as-is. Return ONLY JSON."
    )
    # Chunk into 40-key batches to keep JSON small and reliable.
    keys = list(en_map.keys())
    chunk_size = 40
    result: dict[str, str] = {}
    for i in range(0, len(keys), chunk_size):
        batch_keys = keys[i:i + chunk_size]
        batch = {k: en_map[k] for k in batch_keys}
        prompt = (
            f"Translate every value in the following JSON from English to {lang_name}. "
            f"Return ONLY a JSON object with the same keys and translated values. "
            f"Do not add or remove keys.\n\nInput JSON:\n{json.dumps(batch, ensure_ascii=False)}"
        )
        chat = LlmChat(
            api_key=api_key,
            session_id=f"i18n-{lang_code}-{i}",
            system_message=system_message,
        ).with_model("anthropic", "claude-haiku-4-5-20251001")
        resp = await chat.send_message(UserMessage(text=prompt))
        text = (resp or "").strip()
        if text.startswith("```"):
            text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
            text = re.sub(r"\n?```$", "", text)
        try:
            translated = json.loads(text)
        except json.JSONDecodeError:
            m = re.search(r"\{.*\}", text, re.DOTALL)
            if not m:
                raise
            translated = json.loads(m.group(0))
        result.update({k: str(translated.get(k, en_map[k])) for k in batch_keys})
        print(f"  · {lang_code}: {min(i + chunk_size, len(keys))}/{len(keys)}")
    return result


def emit_ts(lang_code: str, translations: dict[str, str]) -> None:
    """Write a TS module exporting the translated bundle."""
    lines = [
        "/* AUTO-GENERATED by /app/scripts/translate_ui.py. Do not edit by hand. */",
        "import type { TranslationKey } from './strings.en';",
        "",
        f"const t: Partial<Record<TranslationKey, string>> = {{",
    ]
    for k, v in translations.items():
        v_escaped = v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        lines.append(f'  {k}: "{v_escaped}",')
    lines.append("};")
    lines.append("")
    lines.append(f"export default t;")
    lines.append("")
    (ROOT / f"strings.{lang_code}.ts").write_text("\n".join(lines), encoding="utf-8")


async def main():
    en_map = parse_en_object()
    print(f"Parsed {len(en_map)} English keys")
    for code, name in TARGETS:
        out_path = ROOT / f"strings.{code}.ts"
        if out_path.exists():
            print(f"↷ skipping {code} (already exists)")
            continue
        print(f"Translating → {name} ({code}) ...")
        translations = await translate(code, name, en_map)
        emit_ts(code, translations)
        print(f"  ✓ wrote strings.{code}.ts ({len(translations)} keys)")
    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
